# https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml

services:
  sonarqube:
    # si jamais j'ai supp les volumes associés,
    # les login par défaut sur l'interface web c'est admin:admin
    # sinon j'ai mis admin:rootEPSIadmin2025$
    image: sonarqube:community
    hostname: sonarqube
    depends_on:
      db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db/sonarqube
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"

  db:
    image: postgres:17
    hostname: sonarqube-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sonarqube
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d sonarqube -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - sonarqube_db:/var/lib/postgresql

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_db:

networks:
  default:
    name: sonarqube-net  

